### ISSUE TITLE
Uninstall Process

### ISSUE THREAD

**Issue by Dyno75** [DrMeepso/AnitMod#1]
Hello DrMeepso! I apologize for having disturbed you and possibly wasting your time, but I would just like to know how to permanently uninstall this Anticheat, by which I mean so that the command doesn't reappear each startup and reinstall after deleting from appdata.  Thank you in advance and have a good day :)

**Comment by DrMeepso** [comment]
If you remove `Startup.bat` from `C:\Users\%username%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` then remove the files from app data, it will remove it from your system!

Sorry I didn't add this as a feature, I didn't think anyone was ever going to use it lmao

**Comment by DrMeepso** [comment]
Go [here](https://github.com/DrMeepso/AntiMod/blob/main/README.md#removal) for a command to remove
